import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

// Routes that DON'T require a session cookie. They handle their own auth
// (return 401 JSON instead of being middleware-redirected to /login).
//
// Add new public marketing pages to PUBLIC_MARKETING below — not here —
// so the auth-flow surfaces stay grouped separately from public marketing.
const PUBLIC_PATHS = [
  "/login", "/signup", "/forgot-password", "/reset-password", "/verify-email",
  "/invite",
  "/api/auth",   // better-auth handler
  "/api/me",     // api-token endpoint must return 401 not redirect (web client parses JSON)
];

// Public marketing pages — anyone can visit without signing in. Every
// new top-level marketing route MUST be added here, otherwise the
// middleware 307s anonymous visitors to /login, which:
//   • breaks signup funnels (visitor → /runtimes link from a tweet
//     bounces to login → friction)
//   • breaks SEO (Googlebot has no cookie → indexes the /login page
//     instead of the runtime/indie/etc page that should rank)
//   • breaks paid landing pages (UTM-tagged visit bounces to login)
//
// Prefix match (startsWith) — so /runtimes ALSO covers /runtimes/claude etc.
const PUBLIC_MARKETING = [
  "/runtimes",                // hub + /runtimes/{claude,codex,openclaw,hermes}
  "/indie",                   // indie-dev landing
  "/teams",                   // mid-market waitlist (noindex but still public)
  "/connectors",              // connector overview
  "/security",                // security/privacy disclosures
  "/privacy",                 // privacy policy
  "/terms",                   // terms of service
  // Codex review MED: narrowed from "/api/marketing" — future sub-routes
  // under that prefix must be added explicitly so we don't accidentally
  // expose a new auth-needing surface.
  "/api/marketing/event",     // beacon sink (POST only)
];

// SEO / crawler files served as-is. Without this carve-out, the middleware
// redirects /sitemap.xml + /robots.txt to /login, breaking Google Search
// Console submission + every crawler's robots discovery.
const PUBLIC_FILES = new Set(["/sitemap.xml", "/robots.txt", "/favicon.ico"]);

// Next.js App Router icon / OG conventions. Each of these is generated
// by a co-located file (icon.tsx, apple-icon.tsx, opengraph-image.tsx)
// and is fetched WITHOUT a session cookie — by the browser for the tab
// favicon, by iOS for "Add to Home Screen", by Slack/Twitter/etc. when
// they unfurl a link to raltic.com. Without this carve-out the middleware
// 307s them to /login, so:
//   • tab favicon falls back to favicon.ico (works) but Next's dynamic
//     icon.tsx (the higher-res one) never reaches the browser
//   • Apple touch icon → broken
//   • Social share previews → fall back to no-image cards
// Use prefix matching so suffixed variants (/icon-1, /opengraph-image-1)
// generated by Next when multiple files exist also pass through.
const PUBLIC_PREFIXES = ["/icon", "/apple-icon", "/opengraph-image", "/twitter-image"];

// `/` is the public marketing landing — rendered for everyone.
//
// Note: req.nextUrl.pathname NEVER contains "?" or "#" (those live on
// nextUrl.search / .hash).
//
// All non-PREFIX entries now use boundary match (`===` or `startsWith(p+"/")`)
// so e.g. /login-helper or /api/me-internal don't slip past auth via raw
// prefix match. Codex 7 MED.
function matchesBoundary(pathname: string, p: string): boolean {
  return pathname === p || pathname.startsWith(`${p}/`);
}
function isPublicPath(pathname: string): boolean {
  return pathname === "/"
    || PUBLIC_FILES.has(pathname)
    || PUBLIC_PREFIXES.some((p) => pathname === p || pathname.startsWith(`${p}-`) || pathname.startsWith(`${p}/`))
    || PUBLIC_PATHS.some((p) => matchesBoundary(pathname, p))
    || PUBLIC_MARKETING.some((p) => matchesBoundary(pathname, p));
}
// better-auth cookie names are like "better-auth.session_token" in plain
// HTTP and "__Secure-better-auth.session_token" / "__Host-..." over HTTPS.
// Match any of those forms.
function isSessionCookie(name: string): boolean {
  return /(^|__Secure-|__Host-)better-auth\.session_token$/.test(name);
}

/**
 * Security headers applied to every web response. Tight enough that an
 * XSS in our own code can't easily reach an attacker, loose enough that
 * better-auth's OAuth redirects + Next.js inline scripts still work.
 *
 * • CSP: scripts only from self; styles allow inline (Tailwind/JIT
 *   injects a tiny inline style for CSS vars at build time); images +
 *   media from self + data: (avatars / OG). connect-src must include
 *   the API origin so fetch() to api.raltic.com works.
 * • HSTS: only meaningful in production. 1 year + includeSubDomains.
 * • Frame: DENY — Raltic is never iframed (no embed product yet).
 * • Referrer: strict-origin-when-cross-origin — leaks only the origin
 *   to other sites, never full path with workspace slugs.
 * • Permissions-Policy: opt out of features we don't use.
 *
 * Sentry domain added to connect-src to avoid blocking error reports.
 */
// API origin used by `connect-src`. Dev fallback is the local wrangler
// port; without this dev fetches get CSP-blocked when no .env.local sets
// NEXT_PUBLIC_RALTIC_API_URL. Production builds always have the env var.
const IS_DEV = process.env.NODE_ENV !== "production";
const API_ORIGIN =
  process.env.NEXT_PUBLIC_RALTIC_API_URL ?? (IS_DEV ? "http://localhost:8787" : "https://api.raltic.com");

// Sentry origins covered globally so error reports don't get CSP-blocked
// when the SDK posts events from the client.
const SENTRY_DOMAIN = "https://*.ingest.sentry.io https://*.sentry.io";

// Cloudflare Web Analytics (beacon.min.js) needs to be allowed in
// script-src. Without this, the auto-injected analytics script throws
// a CSP violation on every page load (1 console.error per visit) and
// no analytics data is collected. Detected by codex T9 hygiene test.
const CF_INSIGHTS = "https://static.cloudflareinsights.com";

// CSP is mode-aware:
//   • Dev: keep `unsafe-eval` so Next.js HMR works (its dev compiler
//     uses eval); allow `ws://` to local wrangler.
//   • Prod: drop `unsafe-eval` — Next.js 16 production bundles don't
//     need eval. `unsafe-inline` stays because we don't yet emit
//     per-request nonces; nonce-based CSP is a Phase 2 hardening.
//
// Computed at module load so we don't pay the join cost per request.
function wsOriginOf(httpOrigin: string): string {
  return httpOrigin.startsWith("https://")
    ? httpOrigin.replace("https://", "wss://")
    : httpOrigin.replace("http://", "ws://");
}
const CSP_DIRECTIVES = [
  "default-src 'self'",
  IS_DEV
    ? `script-src 'self' 'unsafe-inline' 'unsafe-eval' ${CF_INSIGHTS}`
    : `script-src 'self' 'unsafe-inline' ${CF_INSIGHTS}`,
  "style-src 'self' 'unsafe-inline'",                // Tailwind JIT inline runtime styles
  "img-src 'self' data: blob: https:",               // avatars + OG + uploaded files via R2
  "font-src 'self' data:",
  `connect-src 'self' ${API_ORIGIN} ${wsOriginOf(API_ORIGIN)} ${SENTRY_DOMAIN} ${CF_INSIGHTS}`,
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
].join("; ");

function applySecurityHeaders(res: NextResponse): NextResponse {
  res.headers.set("Content-Security-Policy", CSP_DIRECTIVES);
  res.headers.set("X-Frame-Options", "DENY");
  res.headers.set("X-Content-Type-Options", "nosniff");
  res.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  res.headers.set(
    "Permissions-Policy",
    "accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()",
  );
  // HSTS — 1 year + includeSubDomains. NOT submitted to the HSTS preload
  // list yet: preload commits every raltic.com subdomain to HTTPS forever
  // and is essentially un-reversible (months to undo). We only confirm
  // raltic.com / www / api today; add `preload` after auditing all
  // current+planned subdomains. See docs/OPS.md "HSTS preload checklist".
  res.headers.set("Strict-Transport-Security", "max-age=31536000; includeSubDomains");
  return res;
}

export function proxy(req: NextRequest) {
  const { pathname } = req.nextUrl;
  if (isPublicPath(pathname)) return applySecurityHeaders(NextResponse.next());
  if (pathname.startsWith("/_next") || pathname === "/favicon.ico") {
    return applySecurityHeaders(NextResponse.next());
  }

  const cookies = req.cookies.getAll();
  const hasSession = cookies.some((c) => isSessionCookie(c.name));
  if (!hasSession) {
    return applySecurityHeaders(NextResponse.redirect(new URL("/login", req.url)));
  }
  return applySecurityHeaders(NextResponse.next());
}

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
};
